export const VIDEO_PROGRESS = {
  UPLOADED: 0.1,
  TRANSCODING_STARTED: 0.11,
  TRANSCODING_IN_PROGRESS: 0.15,
  TRANSCODING_COMPLETE: 0.8,
  TRANSCODED_FILES_REGISTERED: 0.81,
  TRANSCODED_FILE_REGISTERED: 0.1,
  DOWNLOADED: 0.8,
  FILES_DSTOR_UPLOAD_COMPLETE: 1.0,
  // otherwise 1.0
}
